# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_file = "../output_data/cities_ARD.csv"
weather_df = pd.read_csv(weather_file, encoding="ISO-8859-1")
weather_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Bredasdorp,-34.53,20.04,42.80,87,15,3.36,ZA,1595809364
1,1,Norman Wells,65.28,-126.83,71.60,46,75,19.46,CA,1595809365
2,2,Moen,69.13,18.61,46.40,93,8,19.46,NO,1595809348
3,3,Saint Simons,31.14,-81.39,86.00,74,20,5.82,US,1595809366
4,4,Coquimbo,-29.95,-71.34,53.60,81,64,2.24,CL,1595809366
...,...,...,...,...,...,...,...,...,...,...
578,578,Grand Gaube,-20.01,57.66,70.00,70,99,8.99,MU,1595809515
579,579,Akureyri,65.68,-18.09,44.60,81,90,9.17,IS,1595809515
580,580,Xining,36.62,101.77,60.96,49,52,3.38,CN,1595809515
581,581,Nangomba,-10.90,38.50,66.87,76,85,4.50,TZ,1595809515
582,582,Boa Vista,2.82,-60.67,80.60,78,40,3.36,BR,1595809414

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]

# Fill NaN values and convert to float
weight = weather_df["Humidity"].astype(float)

In [5]:
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                dissipating=False, max_intensity=100,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
ideal_temp = weather_df[weather_df["Max Temp"] < 80]
ideal_temp = ideal_temp[ideal_temp["Max Temp"] > 70]
ideal_wind = ideal_temp[ideal_temp["Wind Speed"] < 10]
ideal_weather = ideal_wind[ideal_wind["Cloudiness"] == 0]
ideal_weather

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
38,38,Dongsheng,39.82,109.98,71.69,46,0,8.68,CN,1595809377
52,52,Lipari,38.47,14.95,75.99,71,0,4.00,IT,1595809383
191,191,Port Said,31.26,32.28,78.80,83,0,6.93,EG,1595809420
221,221,High Prairie,55.43,-116.49,75.15,54,0,3.58,CA,1595809303
240,240,Areni,39.72,45.18,73.40,56,0,4.70,AM,1595809438
275,275,WaddÄn,29.16,16.14,74.64,44,0,1.19,LY,1595809443
280,280,Province of Trapani,37.83,12.67,75.00,78,0,2.24,IT,1595809446
294,294,Tongzi,28.78,105.09,75.69,90,0,0.69,CN,1595809449
300,300,Vostok,46.49,135.88,75.69,59,0,1.68,RU,1595809451
347,347,Denizli Province,37.84,29.07,71.60,53,0,5.82,TR,1595809457
349,349,Erzin,36.96,36.20,79.00,88,0,1.10,TR,1595809458
366,366,Marsaxlokk,35.84,14.54,78.01,88,0,3.36,MT,1595809460
380,380,Maku,39.29,44.45,73.51,25,0,4.56,IR,1595809462
398,398,Abu Samrah,35.30,37.18,73.49,43,0,1.83,SY,1595809465
439,439,Mahon,39.89,4.27,75.20,78,0,3.36,ES,1595809477
460,460,Constantine,36.37,6.61,78.80,36,0,4.70,DZ,1595809321
529,529,Altamira,-3.20,-52.21,77.56,55,0,1.79,BR,1595809505
545,545,Misratah,32.38,15.09,77.85,78,0,5.44,LY,1595809510
562,562,CassilÃ¢ndia,-19.11,-51.73,70.48,47,0,2.71,BR,1595809513

In [7]:
ideal_weather.describe()

,Unnamed: 0,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.0,19.000000,1.900000e+01
mean,329.789474,32.553684,23.113158,75.344737,61.684211,0.0,3.597895,1.595809e+09
std,146.642263,16.731432,57.815320,2.565685,19.542127,0.0,2.135542,5.711515e+01
min,38.000000,-19.110000,-116.490000,70.480000,25.000000,0.0,0.690000,1.595809e+09
25%,257.500000,31.820000,9.640000,73.500000,46.500000,0.0,1.810000,1.595809e+09
50%,347.000000,36.960000,16.140000,75.200000,56.000000,0.0,3.360000,1.595809e+09
75%,418.500000,39.505000,40.815000,77.705000,78.000000,0.0,4.700000,1.595809e+09
max,562.000000,55.430000,135.880000,79.000000,90.000000,0.0,8.680000,1.595810e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
hotel_df = ideal_weather

In [9]:
# find a hotel for each city located within your coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotels = []

params = {
    "rankby": "distance",
    "keyword": "hotel",
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

    # get lat and lng numbers from df
    lat = row['Lat']
    lng = row['Lng']

    # add location to params
    params['location'] = str(lat) + "," + str(lng)

    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        hotels.append(results[0]['name'])
    except (KeyError, IndexError):
        hotels.append("NA")

In [10]:
print(hotels)

['Senwei Hotel', 'Hotel Villa de Pasquale', 'Port Said Club Hotel', 'Royal Star Motor Inn', 'Areni House B&B', 'Alrwasi Hotel', 'Baglio Donna Franca', "Yong'an Hotel", 'NA', 'Anemon Denizli Hotel', 'Artemis Otel', 'Harbour Lodge', 'كاشانه مهمان صدف', 'Borj hama', 'Hotel Can Roca Nou', 'Hotel El Maghreb', 'Henriques Hotel', 'الصفوة للشقق المفروشة', 'Hotel Rafa Cassilândia']

In [11]:
hotel_df['Hotel Name'] = hotels 
hotel_df = hotel_df.reset_index()

C:\Users\ashle\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [12]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [13]:
hotel_df

,index,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,38,38,Dongsheng,39.82,109.98,71.69,46,0,8.68,CN,1595809377,Senwei Hotel
1,52,52,Lipari,38.47,14.95,75.99,71,0,4.00,IT,1595809383,Hotel Villa de Pasquale
2,191,191,Port Said,31.26,32.28,78.80,83,0,6.93,EG,1595809420,Port Said Club Hotel
3,221,221,High Prairie,55.43,-116.49,75.15,54,0,3.58,CA,1595809303,Royal Star Motor Inn
4,240,240,Areni,39.72,45.18,73.40,56,0,4.70,AM,1595809438,Areni House B&B
5,275,275,WaddÄn,29.16,16.14,74.64,44,0,1.19,LY,1595809443,Alrwasi Hotel
6,280,280,Province of Trapani,37.83,12.67,75.00,78,0,2.24,IT,1595809446,Baglio Donna Franca
7,294,294,Tongzi,28.78,105.09,75.69,90,0,0.69,CN,1595809449,Yong'an Hotel
8,300,300,Vostok,46.49,135.88,75.69,59,0,1.68,RU,1595809451,NA
9,347,347,Denizli Province,37.84,29.07,71.60,53,0,5.82,TR,1595809457,Anemon Denizli Hotel
10,349,349,Erzin,36.96,36.20,79.00,88,0,1.10,TR,1595809458,Artemis Otel
11,366,366,Marsaxlokk,35.84,14.54,78.01,88,0,3.36,MT,1595809460,Harbour Lodge
12,380,380,Maku,39.29,44.45,73.51,25,0,4.56,IR,1595809462,كاشانه مهمان صدف
13,398,398,Abu Samrah,35.30,37.18,73.49,43,0,1.83,SY,1595809465,Borj hama
14,439,439,Mahon,39.89,4.27,75.20,78,0,3.36,ES,1595809477,Hotel Can Roca Nou
15,460,460,Constantine,36.37,6.61,78.80,36,0,4.70,DZ,1595809321,Hotel El Maghreb
16,529,529,Altamira,-3.20,-52.21,77.56,55,0,1.79,BR,1595809505,Henriques Hotel
17,545,545,Misratah,32.38,15.09,77.85,78,0,5.44,LY,1595809510,الصفوة للشقق المفروشة
18,562,562,CassilÃ¢ndia,-19.11,-51.73,70.48,47,0,2.71,BR,1595809513,Hotel Rafa Cassilândia

In [14]:
markers = gmaps.marker_layer(locations)

hotel_layer = gmaps.symbol_layer(locations,
    info_box_content=hotel_info
)

fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))